### ISSUE TITLE
should TLS certificate and keys be saved in the state file?

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#133]
Currently, when the proxy receives a `SaveState` message, all of the frontend and backend information is saved, along with the certificates and keys, in plaintext. Should that information be saved? If yes, do we encrypt it? If no, we probably need to load the certificate and keys separately before we load the state (because some frontends will refer to certificates that are not loaded yet).

**Comment by dns2utf8** [comment]
In my opinion I do not care if the keys are encrypted or not as long as the service can start by it self.

My current scenario: The reverse proxy vm is under constant attack. Since it is running only the bare minimum 512MB RAM should be plenty. For some unknown reason the whole VM crashes every two days. It is most likely due to memory or CPU exhaustion. 

To increase security I was thinking about asking if it were possible for sozu to create, order and sign a TLS certificate on the fly with the acme protocol. This way I could setup the reverse proxy as a read-only VM without any critical data.

**Comment by Geal** [comment]
Just to clarify: are you currently running sozu in production?
Because in the current implementation, it is a bit memory hungry (there are optimizations coming, like #63 and #143), and 512MB would only give you about 30k concurrent connections. If the system fails, that would probably be due to CPU limits.

Support for the acme protocol is not there yet, and will probably not be integrated inside the proxy itself, but it can be an external tool, based on the sozu command library: https://github.com/sozu-proxy/sozu/tree/master/command

Here's how the tool could work:
- start the acme danse
- start a small webserver to host the verification id
- send a message to sozu to start proxying requests to the domain and the specific URL path of the verification id, to that small, local webserver
- the verification is done, the tool receives the certificate
- tell the proxy to stop connecting to the webserver
- stop the webserver
- tell the proxy to start using the new certificate

(maybe this should go in a separate issue)

**Comment by Geal** [comment]
so now there's a tool to get certificates from Let's Encrypt. It ca still be improved a bit, but it can already use sozu to do the HTTP challenge danse: https://github.com/sozu-proxy/sozu-acme

**Comment by Geal** [comment]
considering the current issue, since most of the time the certificates will be on the filesystem already, storing them in the saved state will not change much the security of the system
