### ISSUE TITLE
Unable to compile : openssl errors

### ISSUE THREAD

**Issue by mcorbin** [sozu-proxy/sozu#178]
I'm trying to compile sozu on debian testing but i have these errors :

```
   Compiling sozu-lib v0.1.1
error: no associated item named `get_2048_256` found for type `openssl::dh::Dh` in the current scope
   --> /home/mathieu/.cargo/registry/src/github.com-1ecc6299db9ec823/sozu-lib-0.1.1/src/network/tls.rs:433:11
    |
433 |     match Dh::get_2048_256() {
    |           ^^^^^^^^^^^^^^^^

error: no method named `set_ecdh_auto` found for type `openssl::ssl::SslContextBuilder` in the current scope
   --> /home/mathieu/.cargo/registry/src/github.com-1ecc6299db9ec823/sozu-lib-0.1.1/src/network/tls.rs:441:13
    |
441 |     context.set_ecdh_auto(true);
    |             ^^^^^^^^^^^^^

error: no associated item named `get_2048_256` found for type `openssl::dh::Dh` in the current scope
   --> /home/mathieu/.cargo/registry/src/github.com-1ecc6299db9ec823/sozu-lib-0.1.1/src/network/tls.rs:587:11
    |
587 |     match Dh::get_2048_256() {
    |           ^^^^^^^^^^^^^^^^

error: no method named `set_ecdh_auto` found for type `openssl::ssl::SslContextBuilder` in the current scope
   --> /home/mathieu/.cargo/registry/src/github.com-1ecc6299db9ec823/sozu-lib-0.1.1/src/network/tls.rs:594:9
    |
594 |     ctx.set_ecdh_auto(true);
    |         ^^^^^^^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `sozu-lib`.
```

Any idea how to solve this ?

**Comment by Geal** [comment]
What is your openssl version? you need openssl 1.0.1 or above, as stated in [the rust-openssl README](https://github.com/sfackler/rust-openssl)

**Comment by mcorbin** [comment]
```
openssl version
OpenSSL 1.1.0e  16 Feb 2017
```
So it should be good.

**Comment by Geal** [comment]
that's weird, it should find it easily. Can you try setting up the environment variables: https://github.com/sfackler/rust-openssl#manual-configuration
(you need to clean before rebuilding, because the rust-openssl will not take it into account without a full rebuild)

**Comment by mcorbin** [comment]
I tried 

```
export OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu/ 
export OPENSSL_INCLUDE_DIR=/usr/include/openssl/
cargo clean
cargo build
```

Same errors.

**Comment by Geal** [comment]
with a `cargo build --verbose`? We might see the linker error

**Comment by mcorbin** [comment]
Here are the outputs for `cargo build --verbose` with and without the OPENSSL_* environment variables:

https://pastebin.com/ChmqZwha

I ran an Ubuntu 16.04.2 vagrant box and i was able to compile sozu using it, so something must be wrong with my Debian.

**Comment by BlackYoup** [comment]
I had the same issue and downgraded to `1.0.2k-1~bpo8+1` to make it work but didn't look further

**Comment by Keruspe** [comment]
Yup, OpenSSL 1.1.0 doesn't provide these features so sozu can't build with
it nor with libressl

**Comment by badboy** [comment]
I [patched rust-openssl](https://github.com/badboy/rust-openssl/commit/49ceb328c760081bff55dc6c2e5ad61cb751169c) and now it compiles. I'm gonna report it upstream and see if we can get it fixed.

**Comment by badboy** [comment]
[Done](https://github.com/sfackler/rust-openssl/pull/634)

**Comment by sfackler** [comment]
set_ecdh_auto doesn't exist in OpenSSL 1.1.0. If you're opting into version-specific functionality via the `v101`, `v102` and `v110` features, it's up to you to conditionally compile usage of those methods.

**Comment by Geal** [comment]
@sfackler is there a way in rust-openssl to detect that the feature is incompatible with the currently linked openssl or libressl version? Because it is specified there: https://github.com/sozu-proxy/sozu/blob/master/lib/Cargo.toml#L43 and there's onlyvcf the compilation error on those specific functions.
Do rust-openssl users need to detect the openssl version and set the appropriate features?

**Comment by Geal** [comment]
@sfackler please correct me if I'm wrong (and I first want to state I don't want to diss the excellent work you're doing on rust-openssl, I'm just trying to reach a satisfying solution):

rust-openssl detects the OpenSSL or LibreSSL version in the `build.rs` of `openssl-sys`, and uses it to activate or not the build for some functions. Setting the `v102` feature in sozu's `Cargo.toml` has no effect on which function will be compiled, as it comes from the detection.

So, if I had a sozu feature to activate v102 specific features, it could still end up in the following situations:
- the system has a 1.1 openssl, the v102 feature is active, it does not compile (the current situation)
- the system has a 1.0.2 openssl, the v102 feature is inactive, it compiles but now sozu does not have ECDH available (it will probably fail on this at runtime)

Ideally, I'd want to activate ECDH manually if openssl 1.0.2 is there, and let openssl 1.1 do its thing if that's the currently available version. I could reproduce the `build.rs` of `openssl-sys` on sozu to detect the case at build, but it will be a big chunk of code to keep around, and any openssl user that has the same issue would have to copy that code.

In the way cargo features work, it is the top level project that sets feature on the dependencies, but could it be useful to have dependencies expose system information? Something like "I found this library so now this feature is active", or "I am on this combination of library version and OS, so I'll refuse to compile because it's unsafe"?
Adding a way to get compilation flags from dependencies is probably RFC material, but would it be useful outside of the current issue?

**Comment by sfackler** [comment]
`openssl-sys` emits information about the version of OpenSSL it found at build time. You can depend on it and make a build script that sets some cfgs as appropriate.

Example from openssl itself:
https://github.com/sfackler/rust-openssl/blob/master/openssl/build.rs
https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/connector.rs#L274-L291

You can also just use `SslAcceptor` which deals with this version-specific setup for you. Since you're overriding the cipher list, the only difference between `mozilla_intermediate` and `mozilla_modern` is that `intermediate` sets up Diffie Hellman parameters and modern does not.

**Comment by Geal** [comment]
d268f07 should have fixed it. Thank you @sfackler for your help :)

**Comment by mcorbin** [comment]
It works ;) Thanks !
