### ISSUE TITLE
reorder the commands in sozuctl upgrade

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#282]
The upgrade process allows sozu to change the executable version without losing (too much) traffic.

The upgrade command in sozuctl performs the following actions, in this order:

- get a list of current workers
- launch as many new workers as there are running
- send a soft stop (stop when all connections are done) to all the old workers
- wait for all the new workers to answer, and all the old workers to stop
- upgrade the master process

There are various issues with this process:

- we launch a lot of new workers at the same time, so we will use twice more RAM during the upgrade. The way to avoid the oom killer is then to have the sozu deployment use less than half the server's RAM, which is a bit wasteful
- in tools like htop, at first launch the workers appear to depend from the master process, but after an upgrade, they are all on the same level (not a big issue, but not pleasing to see)
- if a worker takes too much time during its soft stop, it might block the whole upgrade process

Here is how it should be done:

- upgrade the master process (the new process will take over the old workers)
- for each existing worker (one after the other, not all at the same time):
  - start a new worker
  - wait for the new worker to be up
  - soft stop the old worker
  - wait for the old worker to stop

if we upgrade the workers one by one, we only need to leave enough RAM to launch one new worker at any time.

**Comment by roosmaa** [comment]
Thought I'd give this issue a go. Two things I noticed when playing around with sozu & sozuctl upgrade.

Looks like after the master has upgraded itself, the previous socket that the sozuctl is connected to becomes invalid. Haven't really dealt with unix sockets before, but the signs are pointing to that. After the upgrade message has been processed, the launch worker message doesn't ever get a response.

Any preferences on how the reconnecting should be implemented? Handling reconnect (somehow) in the original channel created in ctl/src/main.rs so that it applies to all commands automatically or just have the upgrade command reconnect itself?

Second thing is that whenever I run the upgrade, I end up with more than 2 workers in the end. Looking more closely to it, it looks like that soft stopping workers doesn't really work too well - the master restarts them. I guess it's related the the regression that shutdown command doesn't work anymore #293.

**Comment by roosmaa** [comment]
> Any preferences on how the reconnecting should be implemented? Handling reconnect (somehow) in the original channel created in ctl/src/main.rs so that it applies to all commands automatically or just have the upgrade command reconnect itself?

For now, I'll go with the simplest solution of passing a closure to the upgrade() that is used to creates a new connection. That way I can open PR for this soonish and if need be rework it later :smiley:

**Comment by Geal** [comment]
it should work now, and the soft stop has been fixed as well
