### ISSUE TITLE
Workers being shutdown seems to still accept connections

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#290]
I don't know how to reproduce, but I changed the 404 and 503 pages and did an upgrade. Once the upgrade has been done, some requests were still served by old workers with the old version of those error pages.

A minute or two later, they exited and everything went back to normal

**Comment by Geal** [comment]
so, from what I understand:

- when the worker receives a SoftStop, it deregisters the listen socket, but does not close it
- it continues to accept connections until that listen socket returns WouldBlock (which could happen   much later)
- once it gets a WouldBlock, we're not waiting for any new event. But there could still be new connections (since the kernel will accept them independently)

The right fix would be to implement #147, but it will be a bit tricky to do it right now.
In the meantime, we can do the following:
- deregister the listen socket
- try to accept as many connections as possible until WouldBlock (if we don't have enough buffers available, close them anyway)
- close the listening socket

That means we might lose some connections between the last accept() and the close()

**Comment by Geal** [comment]
hello, does this still happen?

**Comment by BlackYoup** [comment]
I don't know, I couldn't easily reproduce in the first place. Let's close it and re-open if we can trigger it later
