### ISSUE TITLE
Metric to track TLS protocols / ciphers being used

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#495]
So we can now how much clients are using which protocols / ciphers

**Comment by Geal** [comment]
it's a bit tricky because for performance reasons, the current metrics implementation requires keys to be `&'static str`. So right now we will have the protocol version for openssl (we might get the ciphers if https://github.com/sfackler/rust-openssl/issues/961 gets changed), and for rustls we have protocol version and cipher.

Protocol version is under the `tls.version.*` key, like `sozu.WRK-00.tls.version.TLSv1_2`.
Cipher is under the `tls.cipher.*` key, like `sozu.WRK-00.tls.cipher.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`.

current implementation in 6321d6a

**Comment by Geal** [comment]
`SslCipher::name()` now returns a `&'static str`: https://docs.rs/openssl/0.10.11/openssl/ssl/struct.SslCipher.html#method.name

**Comment by Geal** [comment]
fixed in 9d2516d

**Comment by norcalli** [comment]
If it's fixed then this can be closed?

**Comment by Geal** [comment]
I forgot to write it here, but metrics for OpenSSL ciphers will be annoying to display, because the ciphersuites are combinations of a lot of algorithms, so there are dozens of them.
I need a function than transform a openssl `Nid` to a static string, for each ciphersuite.
