### ISSUE TITLE
License : MIT/Apache 

### ISSUE THREAD

**Issue by rohitjoshi** [sozu-proxy/sozu#609]
Appreciate making SŌZU open-source. I do see this becoming alternative to Nginx on some of the use cases.
Any plan to re-licensing under Apache or MIT?

**Comment by johalun** [comment]
Same here. AGPL means a no-go for us.

**Comment by Geal** [comment]
Could you tell me more about your use cases? We'll see if there's a way to meet them

**Comment by johalun** [comment]
I work for a CDN and want to experiment with developing a new reverse proxy using Rust. Sozu would give us a great start but for our use case we would have to modify Sozu significantly. Some parts we can upstream, but there's also a lot of secret sauce that we can't share.

**Comment by rohitjoshi** [comment]
In my case, wanted to evaluate for Nginx ( openresty stack) replacement.

**Comment by StevenLeRoux** [comment]
Agreed. We're also using it. No secret sauce but AGPL can be a showstopper

**Comment by Geal** [comment]
I understand AGPL can be a hard constraint but it is not a closed door. If you need to develop private features, we're open to setting up a support and licensing deal. You should reach out to Quentin Adam, CEO of Clever Cloud, to discuss it (quentin.adam@clever-cloud.com or @waxzce here).
In the meantime, I'd be happy to chat about your technical needs, here or privately if needed (geoffroy.couprie@clever-cloud.com)

**Comment by waxzce** [comment]
Hi,

We are open to give access to others licence, we only want to be sure this will be beneficient for the open source project and non harmful for the company. That's why the project is on dual licencing, so we can grant some companies to OEM the all project easily. Best is to shoot me an email quentin.adam@clever-cloud.com and to have a brief chat about your needs and we can find the good way for all :-)

Best Regards,
