### ISSUE TITLE
no logs after upgrade

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#642]
I had an issue recently where a TCP proxy did not show any logs after an upgrade (proxying worked fine though)

**Comment by Lyamc** [comment]
Had the same thing happen. 

`cargo install sozu` worked just fine for logging
`git clone https://github.com/sozu-proxy/sozu; cd sozu; cargo build --release` didn't work for logging. Used stdout and systemctl for logging. Shame that I lose access logs.

**Comment by Geal** [comment]
I was referring to upgrades done with `sozuctl upgrade`, is that the same for you? Which version did you install with cargo? Which commit from the repository?
Are there no logs at all, or just the access logs missing? How many HTTP requests did you do for the test? Log writes are batched, so the first few logs don't appear right away

**Comment by Lyamc** [comment]
In my case, I had to change my sozu.service from

User=sozu
to
#User=sozu

Which is weird because I gave sozu permissions for all the directories including the log files.

It would not create the log files.

I need to check something else that I suspect is the culprit tomorrow. I’ll retest to confirm

**Comment by Lyamc** [comment]
Figured out the problem, ssd got full, and setting it to root just brute-forced the writes
All is good

**Comment by Geal** [comment]
good to know, thanks
