### ISSUE TITLE
Update build scripts and documentation with the `--locked` flag

### ISSUE THREAD

**Issue by Keksoj** [sozu-proxy/sozu#836]
As demonstrated in this issue:

- #835 

Cargo upgrades minor versions of dependencies, for instance `0.20.6` to `0.20.7`. But Semver rules do NOT force minor versions under `1.0.0` to be non-breaking. As a result, we may meet build errors like in the above issue whenever breaking changes are introduced to new dependencies.

Secure build can alway be performed with 

    cargo build --locked

But we should lock these dependencies.

EDIT: we should actually edit the build scripts and documentation

**Comment by FlorentinDUBOIS** [comment]
Hey, thank you to raise this topic. 

To me, we should not pin crates versions under `1.0.0`, even though it may breaks. Since, I wrote software in Rust, I met this issue a few times. Besides, as you wrote, we could use the `--locked` flag.

I prefer to update scripts and documentations to add the `--locked` flag as it is created to solve this issue.

**Comment by Keksoj** [comment]
Sure! Renaming the issue

**Comment by Keksoj** [comment]
solved by #849
