### ISSUE TITLE
Doubts about the license and the use of sozu

### ISSUE THREAD

**Issue by Juli4nGlobant** [sozu-proxy/sozu#901]
I have a question if sozu can be used as a proxy for projects with a private license (WebApp, API, etc.) without the need to release the code of the projects under the same license.

I would like to use use for a couple of personal projects that i have and maybe in the company where i work, but i am not sure if i can use it given the AGPL license.

**Comment by Keksoj** [comment]
Hello, this limitations have been pointed out before and are an inherent part of the AGPL licence : to use an AGPL licenced software, a business HAS to disclose the source code of all software making use of Sōzu. On top of that, the AGPL licence contaminates the software that uses it.
Using the AGPL licence for Sōzu is a deliberate decision made by Clever Cloud, that owns Sōzu.

The AGPL licence often discourages businesses to use software because they would have to disclose their own code.

**Comment by Geal** [comment]
Saying that CC owns sozu because it's in AGPL is strongly misreading the licence. That's really not what it does

**Comment by Keksoj** [comment]
I did not say Clever Cloud owns Sōzu *because* of the licence. I meant the licence is AGPL *because Clever Cloud owns Sōzu*.

**Comment by Geal** [comment]
No it does not. It's a shared ownership between developers, some of them from Clever Cloud, some of them not. That's a crucial difference
